<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Taskivo-Common/Taskivo-Common.csproj" />
    <ProjectReference Include="../Taskivo-DTO/Taskivo-DTO.csproj" />
    <!-- <ProjectReference Include="../Taskivo-Infrastructure/Taskivo-Infrastructure.csproj" /> -->
    <ProjectReference Include="../Taskivo-Commands/Taskivo-Commands.csproj" />
    <ProjectReference Include="../Taskivo-Queries/Taskivo-Queries.csproj" />
  </ItemGroup>
</Project>
